AWSTemplateFormatVersion: "2010-09-09"

Resources:

  SessionsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Sessions
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
